module.exports = {
  prefix: '',
  important: true,
  separator: ':',
  theme: {
    screens: {},
    colors: {},
    spacing: {
      '2': '0.5rem',
      '3': '0.75rem',
    },
    backgroundColor: {},
    backgroundPosition: {},
    backgroundSize: {},
    borderColor: {},
    borderRadius: {},
    borderWidth: {},
    boxShadow: {},
    container: {},
    cursor: {},
    fill: {},
    flex: {},
    flexGrow: {},
    flexShrink: {},
    fontFamily: {
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
    },
    fontSize: {},
    fontWeight: {
      bold: '700',
    },
    height: {},
    inset: {},
    letterSpacing: {},
    lineHeight: {},
    listStyleType: {},
    margin: {},
    maxHeight: {},
    maxWidth: {},
    minHeight: {},
    minWidth: {},
    objectPosition: {},
    opacity: {},
    order: {},
    padding: theme => theme('spacing'),
    stroke: {},
    textColor: {},
    width: {},
    zIndex: {},
  },
  variants: {
  },
  corePlugins: {},
  plugins: [],
}
